import "../../globals.css";
import Nav from "@/components/nav/Nav";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en ">
      <body
        className={
          inter.className +
          " bg-[#f8f7f7] dark:bg-dmBG flex  items-center h-screen max-lg:block"
        }
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
