import '../../globals.css'
import Nav from "@/components/nav/Nav"
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en " >
      
      <body className={inter.className + ' bg-[#fafafa] dark:bg-dmBG' }> 
        <Nav/>
        { children}
        </body>
    </html>
  )
}
